######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 15 12:06:52 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Container.h TabWidget.h Application.h
SOURCES += main.cpp Container.cpp TabWidget.cpp Application.cpp
RESOURCES += xtab.qrc
OBJECTS_DIR = .obj
MOC_DIR = .moc
RCC_DIR = .qrc
