######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 15 12:06:52 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GlobalShortcut.h 
SOURCES += GlobalShortcut.cpp main.cpp
